// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserQueryClient is the client API for UserQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserQueryClient interface {
	// Sends a greeting
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
}

type userQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryClient(cc grpc.ClientConnInterface) UserQueryClient {
	return &userQueryClient{cc}
}

func (c *userQueryClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := c.cc.Invoke(ctx, "/userApi.v1.UserQuery/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServer is the server API for UserQuery service.
// All implementations must embed UnimplementedUserQueryServer
// for forward compatibility
type UserQueryServer interface {
	// Sends a greeting
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
	mustEmbedUnimplementedUserQueryServer()
}

// UnimplementedUserQueryServer must be embedded to have forward compatible implementations.
type UnimplementedUserQueryServer struct {
}

func (UnimplementedUserQueryServer) GetUser(context.Context, *GetUserRequest) (*GetUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserQueryServer) mustEmbedUnimplementedUserQueryServer() {}

// UnsafeUserQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServer will
// result in compilation errors.
type UnsafeUserQueryServer interface {
	mustEmbedUnimplementedUserQueryServer()
}

func RegisterUserQueryServer(s grpc.ServiceRegistrar, srv UserQueryServer) {
	s.RegisterService(&UserQuery_ServiceDesc, srv)
}

func _UserQuery_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userApi.v1.UserQuery/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQuery_ServiceDesc is the grpc.ServiceDesc for UserQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userApi.v1.UserQuery",
	HandlerType: (*UserQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserQuery_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/userApi/v1/userApi.proto",
}
