// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"userServer/internal/biz"
	"userServer/internal/conf"
	"userServer/internal/data"
	"userServer/internal/server"
	"userServer/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase, err := biz.NewGreeterUsecase(greeterRepo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userQueryService := service.NewUserQueryService(greeterUsecase, logger)
	organQueryService := service.NewOrganQueryService()
	httpServer := server.NewHTTPServer(confServer, userQueryService, organQueryService, logger)
	grpcServer := server.NewGRPCServer(confServer, userQueryService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
